### ISSUE TITLE
Sensor.yaml config isn't correct

### ISSUE THREAD

**Issue by PenguinRage** [ryandanger/up_banking_homeassistant#2]
Had to rewrite to get this working on HA. Example below.

```
# Retrieve Balance
  - platform: rest
    name: up_balances
    resource: https://api.up.com.au/api/v1/accounts
    headers:
      Authorization: !secret up_api
    method: GET
    json_attributes:
      - data
    value_template: 'OK'

  - platform: template
    sensors:
      spending_balance:
        value_template: "{{state_attr('sensor.up_balances', 'data')[0].attributes.balance.value}}"
        unit_of_measurement: '$'
      rainy_day_balance:
        value_template: "{{state_attr('sensor.up_balances', 'data')[1].attributes.balance.value}}"
        unit_of_measurement: '$'
      total_balance:
        value_template: "{{ ((states.sensor.spending_balance.state | float) + (states.sensor.rainy_day_balance.state | float))  | round(2) }}"
        unit_of_measurement: '$'
```
